[server]
port = 3000
workers = 1

[board]
name = "Ferris-chan"
logo = "Ferris-chan.png"
categories = ["Japanese Culture","Interests", "Creative", "Other"]
boards = [
    { name = "Technology", category = "Interests" },
    { name = "Comics & Cartoons", category = "Interests" },
    { name = "Video Games", category = "Interests" },
    { name = "Anime & Manga", category = "Japanese Culture" },
    { name = "Anime/Wallpapers", category = "Japanese Culture" },
    { name = "Anime/Cute", category = "Japanese Culture" },
    { name = "Papercraft & Origami", category = "Creative" },
    { name = "Photography", category = "Creative" },
    { name = "Food & Cooking", category = "Creative" },
    { name = "Politics", category = "Creative" },
    { name = "News", category = "Other" },
    { name = "Health & Fitness", category = "Other" }
]
prevent_anonymous_posts = false
block_registrations = false

[db]
url = ""
type = "sqlite"
username = ""
password = ""