port = 3000
name = "Ferris-chan"
logo = "Ferris-chan.png"
categories = ["Japanese Culture","Interests"]
boards = [{ name = "Technology", category = "Interests" }, { name = "Anime & Manga", category = "Japanese Culture" }]
workers = 1
prevent_anonymous_posts = false
block_registrations = false